In [1]:
import os
import pandas as pd
import tensorflow  as tf
import numpy as np
from  tensorflow import keras
import regex as re
import unicodedata
import string
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

2025-01-12 16:48:00.109143: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-12 16:48:00.213457: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-12 16:48:00.246144: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-12 16:48:01.966638: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
text_file= open('Chatbootdataset/dialogs.txt', 'r')

In [3]:
lines=text_file.readlines()

In [4]:
lines

["hi, how are you doing?\ti'm fine. how about yourself?\n",
 "i'm fine. how about yourself?\ti'm pretty good. thanks for asking.\n",
 "i'm pretty good. thanks for asking.\tno problem. so how have you been?\n",
 "no problem. so how have you been?\ti've been great. what about you?\n",
 "i've been great. what about you?\ti've been good. i'm in school right now.\n",
 "i've been good. i'm in school right now.\twhat school do you go to?\n",
 'what school do you go to?\ti go to pcc.\n',
 'i go to pcc.\tdo you like it there?\n',
 "do you like it there?\tit's okay. it's a really big campus.\n",
 "it's okay. it's a really big campus.\tgood luck with school.\n",
 'good luck with school.\tthank you very much.\n',
 "how's it going?\ti'm doing well. how about you?\n",
 "i'm doing well. how about you?\tnever better, thanks.\n",
 'never better, thanks.\tso how have you been lately?\n',
 "so how have you been lately?\ti've actually been pretty good. you?\n",
 "i've actually been pretty good. you?\ti'm 

In [5]:
question=[]
answer=[]
count=1

In [6]:
for line in lines:
    count+-1
    line_QA=line.strip().split('\t')
    question.append(line_QA[0])
    answer.append(line_QA[1])

In [7]:
question

['hi, how are you doing?',
 "i'm fine. how about yourself?",
 "i'm pretty good. thanks for asking.",
 'no problem. so how have you been?',
 "i've been great. what about you?",
 "i've been good. i'm in school right now.",
 'what school do you go to?',
 'i go to pcc.',
 'do you like it there?',
 "it's okay. it's a really big campus.",
 'good luck with school.',
 "how's it going?",
 "i'm doing well. how about you?",
 'never better, thanks.',
 'so how have you been lately?',
 "i've actually been pretty good. you?",
 "i'm actually in school right now.",
 'which school do you attend?',
 "i'm attending pcc right now.",
 'are you enjoying it there?',
 "it's not bad. there are a lot of people there.",
 'good luck with that.',
 'how are you doing today?',
 "i'm doing great. what about you?",
 "i'm absolutely lovely, thank you.",
 "everything's been good with you?",
 "i haven't been better. how about yourself?",
 'i started school recently.',
 'where are you going to school?',
 "i'm going to pcc.

In [8]:
def unicode_to_ascii(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s)
      if unicodedata.category(c) != 'Mn')

In [9]:
def clean_text(text):
    text = unicode_to_ascii(text.lower().strip())
    text = re.sub(r"i'm", "i am", text)
    text = re.sub(r"\r", "", text)
    text = re.sub(r"he's", "he is", text)
    text = re.sub(r"she's", "she is", text)
    text = re.sub(r"it's", "it is", text)
    text = re.sub(r"that's", "that is", text)
    text = re.sub(r"what's", "that is", text)
    text = re.sub(r"where's", "where is", text)
    text = re.sub(r"how's", "how is", text)
    text = re.sub(r"\'ll", " will", text)
    text = re.sub(r"\'ve", " have", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"\'d", " would", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"can't", "cannot", text)
    text = re.sub(r"n't", " not", text)
    text = re.sub(r"n'", "ng", text)
    text = re.sub(r"'bout", "about", text)
    text = re.sub(r"'til", "until", text)
    text = re.sub(r"[-()\"#/@;:<>{}`+=~|.!?,]", "", text)
    text = text.translate(str.maketrans('', '', string.punctuation)) 
    text = re.sub("(\\W)"," ",text) 
    text = re.sub('\S*\d\S*\s*','', text)
    return text
    

In [10]:
clean_text("the equation 1+1 = 2")

'the equation '

In [11]:
questions=[clean_text(i) for i in question]

In [12]:
answers=[clean_text(i) for i in answer]

In [13]:
questions

['hi how are you doing',
 'i am fine how about yourself',
 'i am pretty good thanks for asking',
 'no problem so how have you been',
 'i have been great what about you',
 'i have been good i am in school right now',
 'what school do you go to',
 'i go to pcc',
 'do you like it there',
 'it is okay it is a really big campus',
 'good luck with school',
 'how is it going',
 'i am doing well how about you',
 'never better thanks',
 'so how have you been lately',
 'i have actually been pretty good you',
 'i am actually in school right now',
 'which school do you attend',
 'i am attending pcc right now',
 'are you enjoying it there',
 'it is not bad there are a lot of people there',
 'good luck with that',
 'how are you doing today',
 'i am doing great what about you',
 'i am absolutely lovely thank you',
 'everythings been good with you',
 'i have not been better how about yourself',
 'i started school recently',
 'where are you going to school',
 'i am going to pcc',
 'how do you like it s

In [14]:
dataset=pd.DataFrame({'source':question,'target':answer})

In [15]:
display(dataset)

source  \
0                                hi, how are you doing?   
1                         i'm fine. how about yourself?   
2                   i'm pretty good. thanks for asking.   
3                     no problem. so how have you been?   
4                      i've been great. what about you?   
...                                                 ...   
3720    that's a good question. maybe it's not old age.   
3721                              are you right-handed?   
3722                                  yes. all my life.   
3723  you're wearing out your right hand. stop using...   
3724        but i do all my writing with my right hand.   

                                                 target  
0                         i'm fine. how about yourself?  
1                   i'm pretty good. thanks for asking.  
2                     no problem. so how have you been?  
3                      i've been great. what about you?  
4              i've been good. i'm in school right now.  
...                                                 ...  
3720                              are you right-handed?  
3721                                  yes. all my life.  
3722  you're wearing out your right hand. stop using...  
3723        but i do all my writing with my right hand.  
3724  start typing instead. that way your left hand ...  

[3725 rows x 2 columns]

In [16]:
dataset['source']=dataset['source'].apply(lambda x: clean_text(x))
dataset['target']=dataset['target'].apply(lambda x: clean_text(x))

In [17]:
dataset

source  \
0                                  hi how are you doing   
1                          i am fine how about yourself   
2                    i am pretty good thanks for asking   
3                       no problem so how have you been   
4                      i have been great what about you   
...                                                 ...   
3720    that is a good question maybe it is not old age   
3721                                are you righthanded   
3722                                    yes all my life   
3723  you are wearing out your right hand stop using...   
3724         but i do all my writing with my right hand   

                                                 target  
0                          i am fine how about yourself  
1                    i am pretty good thanks for asking  
2                       no problem so how have you been  
3                      i have been great what about you  
4             i have been good i am in school right now  
...                                                 ...  
3720                                are you righthanded  
3721                                    yes all my life  
3722  you are wearing out your right hand stop using...  
3723         but i do all my writing with my right hand  
3724  start typing instead that way your left hand w...  

[3725 rows x 2 columns]

In [18]:
dataset['source_len']=dataset['source'].apply(lambda x: len(x.split()))
dataset['target_len']=dataset['source'].apply(lambda x: len(x.split()))

In [19]:
dataset

source  \
0                                  hi how are you doing   
1                          i am fine how about yourself   
2                    i am pretty good thanks for asking   
3                       no problem so how have you been   
4                      i have been great what about you   
...                                                 ...   
3720    that is a good question maybe it is not old age   
3721                                are you righthanded   
3722                                    yes all my life   
3723  you are wearing out your right hand stop using...   
3724         but i do all my writing with my right hand   

                                                 target  source_len  \
0                          i am fine how about yourself           5   
1                    i am pretty good thanks for asking           6   
2                       no problem so how have you been           7   
3                      i have been great what about you           7   
4             i have been good i am in school right now           7   
...                                                 ...         ...   
3720                                are you righthanded          11   
3721                                    yes all my life           3   
3722  you are wearing out your right hand stop using...           4   
3723         but i do all my writing with my right hand          12   
3724  start typing instead that way your left hand w...          10   

      target_len  
0              5  
1              6  
2              7  
3              7  
4              7  
...          ...  
3720          11  
3721           3  
3722           4  
3723          12  
3724          10  

[3725 rows x 4 columns]

In [20]:
max_source, max_target = max(dataset['source_len']), max(dataset['target_len'])

In [21]:
max_source,max_target

(20, 20)

In [22]:
def tokenize(lang):
    lang_tokenizer = tf.keras.preprocessing.text.Tokenizer(
      filters='')
    lang_tokenizer.fit_on_texts(lang)
    tensor = lang_tokenizer.texts_to_sequences(lang)

    tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor,
                                                         padding='post')

    return tensor, lang_tokenizer

In [60]:
tokenizer = Tokenizer(num_words=10000,filters='')
tokenizer.fit_on_texts(questions + answers)

question_sequences = tokenizer.texts_to_sequences(questions)
answer_sequences = tokenizer.texts_to_sequences(answers)
    #Pad Sequences
max_length = 20
padded_question_sequences = pad_sequences(question_sequences, maxlen=max_length)
padded_answer_sequences = pad_sequences(answer_sequences, maxlen=max_length)

In [61]:
padded_answer_sequences


array([[  0,   0,   0, ...,  35,  33, 524],
       [  0,   0,   0, ..., 230,  27, 460],
       [  0,   0,   0, ...,  12,   2,  93],
       ...,
       [  0,   0,   0, ...,   6,  22,  78],
       [  0,   0,   0, ...,  28,  64, 396],
       [  0,   0,   0, ..., 513,   3, 149]], dtype=int32)

In [62]:
padded_answer_sequences[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   1,  25, 574,  35,  33, 524], dtype=int32)

In [26]:
index=tokenizer.word_index

In [27]:
index

{'i': 1,
 'you': 2,
 'the': 3,
 'is': 4,
 'to': 5,
 'it': 6,
 'a': 7,
 'that': 8,
 'not': 9,
 'do': 10,
 'are': 11,
 'have': 12,
 'what': 13,
 'will': 14,
 'of': 15,
 'and': 16,
 'did': 17,
 'they': 18,
 'in': 19,
 'he': 20,
 'was': 21,
 'so': 22,
 'like': 23,
 'we': 24,
 'am': 25,
 'yes': 26,
 'for': 27,
 'my': 28,
 'but': 29,
 'no': 30,
 'be': 31,
 'me': 32,
 'about': 33,
 'on': 34,
 'how': 35,
 'go': 36,
 'think': 37,
 'too': 38,
 'why': 39,
 'your': 40,
 'would': 41,
 'going': 42,
 'good': 43,
 'with': 44,
 'want': 45,
 'really': 46,
 'get': 47,
 'know': 48,
 'well': 49,
 'at': 50,
 'all': 51,
 'there': 52,
 'one': 53,
 'just': 54,
 'she': 55,
 'can': 56,
 'this': 57,
 'should': 58,
 'if': 59,
 'people': 60,
 'see': 61,
 'does': 62,
 'then': 63,
 'right': 64,
 'nice': 65,
 'out': 66,
 'time': 67,
 'need': 68,
 'her': 69,
 'money': 70,
 'oh': 71,
 'maybe': 72,
 'him': 73,
 'course': 74,
 'lot': 75,
 'when': 76,
 'or': 77,
 'much': 78,
 'okay': 79,
 'got': 80,
 'up': 81,
 'cannot': 8

In [28]:
len(index)

2408

In [29]:
def positional_enconding(length, depth):
    depth=depth/2
    
    positions= np.arange(length)[:, np.newaxis]
    depth=np.arange(depth)[np.newaxis, :]/depth
    
    angle_rates= 1/(10000**depth)
    angle_rads=positions*angle_rates
    
    pos_enconding=np.concatenate([np.sin(angle_rads), np.cos(angle_rads)], axis=-1)
    return tf.cast(pos_enconding,  dtype=tf.float32)

In [30]:
class PositionalEmbedding(tf.keras.layers.Layer):
    def __init__(self, vocab_size, d_model):
        super().__init__()
        self.d_model=d_model
        self.embedding=tf.keras.layers.Embedding(vocab_size,d_model,mask_zero=True)
        #positional enconding function
        self.pos_enconding=positional_enconding(length=2048, depth=d_model)
        
    #def compute_mask(self, *args, **kwagrs):
     #   return self.embedding.compute_mask(*args, **kwargs)
    
    def call(self, x):
        length=tf.shape(x)[1]
        x=self.embedding(x)
        
        x*=tf.math.sqrt(tf.cast(self.d_model, tf.float32))
        x=x+self.pos_enconding[np.newaxis, :length, :]
        return x

In [31]:
input_tensor = tf.random.uniform((32, 512, 256))
input_tensor=tf.cast(input_tensor,tf.float32)
vocab_size = 50000#input_tensor.shape[-1]  # 256
embedding_dim = 512

#positional_encoding = PositionalEncoding(vocab_size, embedding_dim)
#position_embeddings = positional_encoding(input_tensor)

#print(position_embeddings.shape)  # (256, 256)

In [32]:
input_embeddings = tf.random.uniform((len(questions), max_length, embedding_dim))
input_embeddings.shape[-1]

512

In [33]:
input_embeddings.shape[-1]

512

In [34]:
input_embeddings[0]

<tf.Tensor: shape=(20, 512), dtype=float32, numpy=
array([[6.1128950e-01, 3.2426608e-01, 1.7701054e-01, ..., 4.2234468e-01,
        4.5258927e-01, 6.7215824e-01],
       [4.3715584e-01, 5.9550226e-01, 3.5030127e-02, ..., 3.1237364e-01,
        1.2576580e-04, 3.0767572e-01],
       [2.2387242e-01, 8.9852822e-01, 6.6860628e-01, ..., 1.1883557e-01,
        3.9444470e-01, 1.2712002e-01],
       ...,
       [6.9143057e-02, 5.5248523e-01, 8.4702647e-01, ..., 8.3785737e-01,
        9.0761614e-01, 9.5183575e-01],
       [4.3331468e-01, 8.8957071e-01, 6.3492811e-01, ..., 1.6253138e-01,
        1.2837088e-01, 3.6723697e-01],
       [1.0498881e-01, 2.9974794e-01, 7.0796514e-01, ..., 9.4755685e-01,
        7.3822284e-01, 8.3382523e-01]], dtype=float32)>

In [35]:
embed_pt = PositionalEmbedding(vocab_size=50000, d_model=512) #tokenizers. pt.get_vocab_size(), d_model=512)
embed_en = PositionalEmbedding(vocab_size=50000, d_model=512)

In [36]:
padded_question_sequences[5]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,  12,  93,
        43,   1,  25,  19,  87,  64, 104], dtype=int32)

In [37]:
embed_en(padded_question_sequences)

<tf.Tensor: shape=(3725, 20, 512), dtype=float32, numpy=
array([[[ 0.45301378,  0.6311702 , -0.5391414 , ...,  1.1571467 ,
          0.48234123,  1.4805987 ],
        [ 1.2944847 ,  1.4530264 ,  0.26282036, ...,  1.1571467 ,
          0.48234123,  1.4805987 ],
        [ 1.3623111 ,  1.567585  ,  0.41900295, ...,  1.1571467 ,
          0.48234123,  1.4805987 ],
        ...,
        [-1.9239279 ,  0.42161137, -0.7627955 , ...,  0.22996706,
          1.262395  ,  0.955319  ],
        [-1.0365616 , -1.9229821 , -0.15864211, ...,  1.1096501 ,
          0.5930217 ,  0.8576412 ],
        [-0.79543304, -0.21789837, -1.9117213 , ...,  0.6775141 ,
          1.9066844 ,  0.85991454]],

       [[ 0.45301378,  0.6311702 , -0.5391414 , ...,  1.1571467 ,
          0.48234123,  1.4805987 ],
        [ 1.2944847 ,  1.4530264 ,  0.26282036, ...,  1.1571467 ,
          0.48234123,  1.4805987 ],
        [ 1.3623111 ,  1.567585  ,  0.41900295, ...,  1.1571467 ,
          0.48234123,  1.4805987 ],
        ..

In [38]:
pt_emb = embed_pt(padded_question_sequences)
en_emb = embed_en(padded_answer_sequences)

In [39]:
pt_emb

<tf.Tensor: shape=(3725, 20, 512), dtype=float32, numpy=
array([[[-0.21496402,  0.32742748, -1.0948896 , ...,  1.3920825 ,
          0.11417145,  0.72438526],
        [ 0.6265069 ,  1.1492836 , -0.29292786, ...,  1.3920825 ,
          0.11417145,  0.72438526],
        [ 0.6943334 ,  1.2638422 , -0.13674527, ...,  1.3920825 ,
          0.11417145,  0.72438526],
        ...,
        [-1.2586397 , -1.7544866 ,  0.95940906, ..., -0.11986601,
          0.6723125 , -0.10420036],
        [-1.6257845 , -0.27090573, -1.9370615 , ...,  0.31080705,
          0.34299743,  1.3499302 ],
        [-0.3178131 , -1.0875665 , -0.81261706, ...,  1.6713674 ,
          0.9588311 , -0.01169139]],

       [[-0.21496402,  0.32742748, -1.0948896 , ...,  1.3920825 ,
          0.11417145,  0.72438526],
        [ 0.6265069 ,  1.1492836 , -0.29292786, ...,  1.3920825 ,
          0.11417145,  0.72438526],
        [ 0.6943334 ,  1.2638422 , -0.13674527, ...,  1.3920825 ,
          0.11417145,  0.72438526],
        ..

In [40]:
class BaseAttention(tf.keras.layers.Layer):
    def __init__(self,**kwagrs):
        super().__init__()
        self.mha=keras.layers.MultiHeadAttention(**kwagrs)
        self.layernorm=keras.layers.LayerNormalization()
        self.add=keras.layers.Add()

In [41]:
class CrossAttention(BaseAttention):
    def call(self, x, context):
        attn_output, attn_score =self.mha(query=x, key=context, value=context, return_attention_scores=True)
        
        #cache the attention score for plotting later
        self.last_attn_score=attn_score
        
        x=self.add([x, attn_output])
        x=self.layernorm(x)
        
        return x

In [42]:
class GlobalSelfAttention(BaseAttention):
    def call(self, x):
        attn_output=self.mha(query=x, value=x, key=x)
        x=self.add([x, attn_output])
        x=self.layernorm(x)
        return x

In [43]:
sample_gsa = GlobalSelfAttention(num_heads=2, key_dim=512)

print(pt_emb.shape)
print(sample_gsa(pt_emb).shape)

(3725, 20, 512)


2025-01-12 16:48:09.254280: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 305152000 exceeds 10% of free system memory.
2025-01-12 16:48:11.594289: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 305152000 exceeds 10% of free system memory.
2025-01-12 16:48:11.674935: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 305152000 exceeds 10% of free system memory.
2025-01-12 16:48:13.019960: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 305152000 exceeds 10% of free system memory.
2025-01-12 16:48:13.105722: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 305152000 exceeds 10% of free system memory.


(3725, 20, 512)


In [44]:
class CasualSelfAttention(BaseAttention):
    def call(self,x):
        attn_output=self.mha(query=x,value=x, key=x)#, use_casual_mask = True)
        x=self.add([x,attn_output])
        x=self.layernorm(x)
        return x

In [45]:
class FeedForward(tf.keras.layers.Layer):
    def __init__(self,  d_model, dff, dropout=0.1):
        super().__init__()
        self.sequence=tf.keras.Sequential([tf.keras.layers.Dense(dff, activation="relu"),
                                          tf.keras.layers.Dense(d_model),
                                          tf.keras.layers.Dropout(dropout)])
        self.add=tf.keras.layers.Add()
        self.layer_norm=tf.keras.layers.LayerNormalization()
        
    def call(self, x):
        x=self.add([x, self.sequence(x)])
        x=self.layer_norm(x)
        return x

In [46]:
class EncoderLayer(tf.keras.layers.Layer):
    def __init__(self, *, d_model, num_heads, dff, dropout_rate=0.1):
        super().__init__()
        self.self_attention=GlobalSelfAttention(num_heads=num_heads, key_dim=d_model)#,dropout=dropout_rate)
        self.fnn=FeedForward(d_model,dff)
    def call(self,x):
        x=self.self_attention(x)
        x=self.fnn(x)
        return x

In [47]:
class Encoder(tf.keras.layers.Layer):
    def __init__(self, *, num_layers, d_model, num_heads, dff, vocab_size, dropout_rate=0.1):
        super().__init__()
        self.d_model=d_model
        self.num_layers=num_layers
        
        self.pose_embedding=PositionalEmbedding(vocab_size=vocab_size, d_model=d_model)
        self.enc_layers=[EncoderLayer(d_model=d_model, num_heads=num_heads,dff=dff, dropout_rate=dropout_rate) for _ in range(num_layers)]
        self.dropout=tf.keras.layers.Dropout(dropout_rate)
        
    def call(self, x):
            
        x=self.pose_embedding(x)
        x=self.dropout(x)
            
        for i in range(self.num_layers):
            x=self.enc_layers[i](x)
        return x

In [48]:
class DecoderLayer(tf.keras.layers.Layer):
    def __init__(self, *, d_model, num_heads,dff, dropout_rate=0.1):
        super(DecoderLayer, self).__init__()
        self.casual_self_attention=CasualSelfAttention(num_heads=num_heads, key_dim=d_model, dropout=dropout_rate)
        
        self.cross_attendtion=CrossAttention(num_heads=num_heads, key_dim=d_model, dropout=dropout_rate)
        
        self.ffn=FeedForward(d_model,dff)
    def call(self, x, context):
        x=self.casual_self_attention(x=x)
        x=self.cross_attendtion(x=x,context=context)
        self.last_attn_score=self.cross_attendtion.last_attn_score
        
        x=self.ffn(x)
        return x

In [49]:
class Decoder(tf.keras.layers.Layer):
    def __init__(self, *, num_layers, d_model, num_heads, dff, vocab_size, dropout_rate=0.1):
        super(Decoder, self).__init__()
        self.d_model=d_model
        self.num_layer=num_layers
        
        self.pos_embedding=PositionalEmbedding(vocab_size=vocab_size,d_model=d_model)
        self.dropout=tf.keras.layers.Dropout(dropout_rate)
        
        self.dec_layers=[DecoderLayer(d_model=d_model, num_heads=num_heads,dff=dff,dropout_rate=dropout_rate) for _ in range(num_layers)]
        self.last_attn_scores=None
    
    def call(self, x,  context):
        x=self.pos_embedding(x)
        x=self.dropout(x)
        
        for i in range(self.num_layer):
            x=self.dec_layers[i](x, context)
        
        self.last_attn_scores=self.dec_layers[-1].last_attn_score
        
        return x

In [50]:
class Transformer(tf.keras.Model):
    def __init__(self, *, num_layers,d_model,num_heads,dff,input_vocab_size,target_vocab_size,dropout_rate=0.1):
        super().__init__()
        self.encoder=Encoder(num_layers=num_layers,num_heads=num_heads, d_model=d_model,dff=dff,
                             vocab_size=50000, dropout_rate=dropout_rate)
    
        self.decoder=Decoder(num_layers=num_layers,d_model=d_model,
                            num_heads=num_heads,dff=dff,
                            vocab_size=50000,dropout_rate=dropout_rate)
    
        self.final_layer=tf.keras.layers.Dense(target_vocab_size)
    def call(self, inputs):
        context, x = inputs
        
        context= self.encoder(context)
        x=self.decoder(x, context)
        
        logits=self.final_layer(x)
        
        try:
            del logits._keras_mask
        except AttributeError:
            pass
        return logits
    

In [51]:
num_layers = 4
d_model = 128
dff = 512
num_heads = 8
dropout_rate = 0.1

In [52]:
transformer = Transformer(
    num_layers=num_layers,
    d_model=d_model,
    num_heads=num_heads,
    dff=dff,
    input_vocab_size=20,#tokenizers.pt.get_vocab_size().numpy(),
    target_vocab_size=20,#tokenizers.en.get_vocab_size().numpy(),
    dropout_rate=dropout_rate)

In [53]:
inputs=(padded_question_sequences, padded_answer_sequences)

In [54]:
output = transformer(inputs)


In [56]:
output.shape

TensorShape([3725, 20, 20])

In [70]:
token_indices = tf.argmax(output, axis=-1) 

In [71]:
token_indices

<tf.Tensor: shape=(3725, 20), dtype=int64, numpy=
array([[16, 16, 16, ..., 12, 12, 12],
       [16, 16, 16, ..., 12, 13, 15],
       [16, 16, 16, ..., 12, 12, 12],
       ...,
       [16, 16, 16, ..., 13, 12, 12],
       [16, 16, 16, ..., 12, 12, 13],
       [16, 16, 16, ..., 12,  1, 12]])>

In [57]:
class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):
  def __init__(self, d_model, warmup_steps=4000):
    super().__init__()

    self.d_model = d_model
    self.d_model = tf.cast(self.d_model, tf.float32)

    self.warmup_steps = warmup_steps

  def __call__(self, step):
    step = tf.cast(step, dtype=tf.float32)
    arg1 = tf.math.rsqrt(step)
    arg2 = step * (self.warmup_steps ** -1.5)

    return tf.math.rsqrt(self.d_model) * tf.math.minimum(arg1, arg2)

In [59]:
tokenizer.document_count

7450

In [72]:
decoded_texts = [
    ' '.join([tokenizer.index_word.get(idx, '[UNK]') for idx in sequence])
    for sequence in token_indices.numpy()
]
for text in decoded_texts:
    print("Decoded Text:", text)

Decoded Text: and and and the the they they they they of of of of of what what i have have have
Decoded Text: and and and the the they they they of of of of of what what have have have what of
Decoded Text: and and and the the they they they of of of of of what in to have have have have
Decoded Text: and and and the the they they they of of of of of what in have in have have have
Decoded Text: and and and the the they they they they of what in of not what what have what have have
Decoded Text: and and and the the they they they of of of of of of what to what have what have
Decoded Text: and and and the the they they they of of of of of of have have what what have have
Decoded Text: and and and the the they they they of of of of of of have what have have of of
Decoded Text: and and and the the they they they they of of of to to what what to have have have
Decoded Text: and and and the the they they they of of of of of of have have have have have they
Decoded Text: and and and the the th